import { redirect } from "next/navigation";
import { obtenirUtilisateurConnecte } from "@/lib/session";
import { obtenirOuCreerEcole } from "@/lib/ecole";
import { prisma } from "@/lib/prisma";
import AdminShell from "@/components/admin/AdminShell";
import { creer, basculer } from "./actions";
import styles from "../finances-enterprise.module.css";
export const dynamic="force-dynamic";
export default async function Page(){const u=await obtenirUtilisateurConnecte();if(!u)redirect("/connexion");const e=await obtenirOuCreerEcole();const rows=await prisma.$queryRaw<Array<{id:number;code:string;libelle:string;description:string|null;actif:number|boolean}>>`SELECT id,code,libelle,description,actif FROM categories_frais_scolaires WHERE ecole_id=${e.id} ORDER BY libelle`;return <AdminShell utilisateur={u} titre="Catégories de frais" description="Paramétrage financier de l'établissement."><div className={styles.page}><section className={styles.panel}><h3>Nouvel élément</h3><form action={creer} className={styles.form}><label><span>Code *</span><input name="code" required/></label><label><span>Libellé *</span><input name="libelle" required/></label><label className={styles.large}><span>Description</span><textarea name="description"/></label><label><input type="checkbox" name="actif" defaultChecked/> Actif</label><button className={styles.btn}>Enregistrer</button></form></section><section className={styles.panel}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Code</th><th>Libellé</th><th>Description</th><th>Statut</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.code}</strong></td><td>{r.libelle}</td><td>{r.description??"—"}</td><td><span className={styles.badge}>{r.actif?"ACTIF":"INACTIF"}</span></td><td><form action={basculer.bind(null,r.id,Boolean(r.actif))}><button className={styles.btn}>{r.actif?"Désactiver":"Activer"}</button></form></td></tr>)}</tbody></table></div></section></div></AdminShell>}
