import Link from "next/link"; import { redirect } from "next/navigation"; import { Filter, Plus, Search } from "lucide-react";
import { prisma } from "@/lib/prisma"; import { obtenirUtilisateurConnecte } from "@/lib/session"; import { obtenirOuCreerEcole } from "@/lib/ecole"; import AdminShell from "@/components/admin/AdminShell";
import RetourDashboard from "../RetourDashboard"; import { ProspectCRM, ETAPES_CRM, libelleStatut } from "../types"; import styles from "../crm.module.css";
export const dynamic="force-dynamic";
type Props={searchParams:Promise<{q?:string;statut?:string;relance?:string;succes?:string}>};
export default async function Page({searchParams}:Props){const utilisateur=await obtenirUtilisateurConnecte();if(!utilisateur)redirect("/connexion");const ecole=await obtenirOuCreerEcole();const p=await searchParams;let prospects=await prisma.$queryRaw<ProspectCRM[]>`SELECT * FROM crm_prospects WHERE ecole_id=${ecole.id} ORDER BY created_at DESC`;
 const q=(p.q||"").toLowerCase(); if(q) prospects=prospects.filter(x=>[x.nom_eleve,x.prenom_eleve,x.nom_responsable,x.telephone,x.code].some(v=>String(v||"").toLowerCase().includes(q))); if(p.statut)prospects=prospects.filter(x=>x.statut===p.statut); if(p.relance==="1")prospects=prospects.filter(x=>x.prochaine_relance&&new Date(x.prochaine_relance)<=new Date()&&!['INSCRIPTION','PERDU'].includes(x.statut));
 return <AdminShell utilisateur={utilisateur} titre="Prospects CRM" description="Centralisez les familles intéressées et suivez chaque opportunité jusqu’à l’inscription." action={<Link className={styles.primaire} href="/dashboard/crm/prospects/nouveau"><Plus size={18}/> Nouveau prospect</Link>}><RetourDashboard/>{p.succes&&<div className={styles.succes}>Prospect créé avec succès.</div>}
 <form className={styles.filtres}><Search size={18}/><input name="q" defaultValue={p.q} placeholder="Nom, téléphone, code..."/><select name="statut" defaultValue={p.statut||""}><option value="">Toutes les étapes</option>{ETAPES_CRM.map(([c,l])=><option key={c} value={c}>{l}</option>)}</select><button><Filter size={17}/> Filtrer</button></form>
 <section className={styles.panneau}><div className={styles.tableWrap}><table><thead><tr><th>Apprenant / code</th><th>Responsable</th><th>Classe souhaitée</th><th>Source</th><th>Étape</th><th>Priorité</th><th>Action</th></tr></thead><tbody>{prospects.map(x=><tr key={x.id}><td><strong>{x.nom_eleve} {x.prenom_eleve||""}</strong><small>{x.code}</small></td><td>{x.nom_responsable}<small>{x.telephone}</small></td><td>{x.classe_souhaitee||"—"}</td><td>{x.source}</td><td><span className={styles.badge}>{libelleStatut(x.statut)}</span></td><td><span className={`${styles.priorite} ${styles[x.priorite.toLowerCase()]||""}`}>{x.priorite}</span></td><td><Link className={styles.voir} href={`/dashboard/crm/prospects/${x.id}`}>Ouvrir</Link></td></tr>)}</tbody></table>{!prospects.length&&<div className={styles.vide}>Aucun prospect ne correspond aux filtres.</div>}</div></section></AdminShell>}
